// <auto-generated />
namespace LATravelManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _121804273 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_121804273));
        
        string IMigrationMetadata.Id
        {
            get { return "201812181428078_121804273"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
