// <auto-generated />
namespace LATravelManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _119 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_119));
        
        string IMigrationMetadata.Id
        {
            get { return "201811091432185_119"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
