// <auto-generated />
namespace LATravelManager.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _54 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_54));
        
        string IMigrationMetadata.Id
        {
            get { return "201902051221526_54"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
