// <auto-generated />
namespace LATravelManager.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class _1215 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1215));
        
        string IMigrationMetadata.Id
        {
            get { return "201912142311579_1215"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
