// <auto-generated />
namespace LATravelManager.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class service : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(service));
        
        string IMigrationMetadata.Id
        {
            get { return "202004240926388_service"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
