// <auto-generated />
namespace LATravelManager.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class deleteInvoices : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deleteInvoices));
        
        string IMigrationMetadata.Id
        {
            get { return "202101071742248_deleteInvoices"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
