// <auto-generated />
namespace LATravelManager.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class requiredRecieptStuff : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(requiredRecieptStuff));
        
        string IMigrationMetadata.Id
        {
            get { return "202101101906279_requiredRecieptStuff"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
